# ───────────────────────────────────────────────────────────────────────────────
# Service  (NLB + external-dns)
# ───────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: dev-voxel-builder
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:975050212377:certificate/64f8866a-e9aa-4ab2-a737-49a97a366c44
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: "voxel-builder.dev.hyve.gg"
spec:
  type: LoadBalancer
  selector:
    app: dev-voxel-builder
  ports:
    - name: http
      port: 80           # clients hit port 80 on the NLB
      targetPort: 8011   # forwarded to container port
      protocol: TCP
    - name: https
      port: 443           # clients hit port 443 on the NLB
      targetPort: 8011   # forwarded to container port
      protocol: TCP
